import { LightningElement } from 'lwc';
import {NavigationMixin} from 'lightning/navigation';
import {encodeDefaultFieldValues} from 'lightning/pageReferenceUtils';
export default class NavigateHome extends NavigationMixin(LightningElement) {

    navigateToHome(){
        this[NavigationMixin.Navigate]({
            type:'standard__namedPage',
            attributes:{
                pageName:'home'
            }    
        })
    }
    navigateToChatter(){
        this[NavigationMixin.Navigate]({
            type:'standard__namedPage',
            attributes:{
                pageName:'chatter'
            }    
        })
    }
    navigateToNewRecord(){
        this[NavigationMixin.Navigate]({
            type:'standard__objectPage',
            attributes:{
                objectApiName:'Account',
                actionName:'new'
            }    
        })
    }
    navigateToNewRecordWithDefault(){
        const defaultValues = encodeDefaultFieldValues({
            Name:'Ankit',
            Phone:'768776567'
        })
        this[NavigationMixin.Navigate]({
            type:'standard__objectPage',
            attributes:{
                objectApiName:'Account',
                actionName:'new'
            },
            state:{
                defaultFieldValues : defaultValues
            }    
        })
    }
    navigateToListView(){
        this[NavigationMixin.Navigate]({
            type:'standard__objectPage',
            attributes:{
                objectApiName:'Account',
                actionName:'list'
            }
        })
    }
    navigateToFiles(){
        this[NavigationMixin.Navigate]({
            type:'standard__objectPage',
            attributes:{
                objectApiName:'ContentDocument',
                actionName:'home'
            }
        })
    }
    navigateRecordInViewMode(){
        this[NavigationMixin.Navigate]({
            type:'standard__recordPage',
            attributes:{
                recordId:'003N000001pv3pIIAQ',
                objectApiName:'Contact',
                actionName:'view'
            }
        })
    }
    navigateRecordInEditMode(){
        this[NavigationMixin.Navigate]({
            type:'standard__recordPage',
            attributes:{
                recordId:'003N000001pv3pIIAQ',
                objectApiName:'Contact',
                actionName:'edit'
            }
        })
    }
    navigateTofacebook(){
        this[NavigationMixin.Navigate]({
            type:'standard__webPage',
            attributes:{
                url:"http://www.facebook.com/ankit556"
            }
        })
    }
    navigateToRelatedContact(){
        this[NavigationMixin.Navigate]({
            type:'standard__recordRelationshipPage',
            attributes:{
                recordId:'001N0000022vG4TIAU',
                objectApiName:'Account',
                relationshipApiName:'Contacts',
                actionName:'view'
            }
        })
    }

    navigateToTab(){
        this[NavigationMixin.Navigate]({
            type:'standard__navItemPage',
            attributes:{
                apiName:'Memory_Game'
            }
        })
    }
}